kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: docker.io/sergiogm1/react-app:1.0
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-docker 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110